### ISSUE TITLE
دانلود سرباز اضافه

### ISSUE THREAD

**Issue by VahidDopler** [DarkDeveloper-arch/BitKip#1]
![image](https://github.com/DarkDeveloper-arch/BitKip/assets/77194408/566ec541-04c2-4bf9-88fd-0ca1a959e8a6)
هنگامی که لینک غیر قابل دانلود باشه و حجمش نامشخص باشه، برنامه به دلیل عدم دریافت حجم شروع به دانلود سربار میکنه

**Comment by DarkDeveloper-arch** [comment]
fixed on links_without_size_header branch
